language: cpp

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo perl devkitARMupdate.pl
  - wget --no-check-certificate https://codeload.github.com/smealum/ctrulib/zip/master -O /tmp/ctrulib.zip
  - unzip /tmp/ctrulib.zip
  - cd ctrulib-master/libctru
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/fincs/citro3d/zip/master -O /tmp/citro3d.zip
  - unzip /tmp/citro3d.zip
  - cd citro3d-master
  - make && sudo make install
  - cd ..  
  - wget --no-check-certificate https://github.com/xerpi/3ds_portlibs/releases/download/1/portlibs-linux.zip -O /tmp/3ds_portlibs.zip
  - unzip /tmp/3ds_portlibs.zip
  - cp -R /tmp/portlibs ${DEVKITPRO}/
  - wget --no-check-certificate https://codeload.github.com/xerpi/sf2dlib/zip/master -O /tmp/sf2dlib.zip
  - unzip /tmp/sf2dlib.zip
  - cd sf2dlib-master/libsf2d
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/xerpi/sfillib/zip/master -O /tmp/sfillib.zip
  - unzip /tmp/sfillib.zip
  - cd sfillib-master/libsfil
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/xerpi/sftdlib/zip/master -O /tmp/sftdlib.zip
  - unzip /tmp/sftdlib.zip
  - cd sftdlib-master/libsftd
  - make && sudo make install
  - cd ../..
  
script:
  - make
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp