language: cpp

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo perl devkitARMupdate.pl  
  - wget --no-check-certificate https://codeload.github.com/smealum/ctrulib/zip/master -O /tmp/ctrulib.zip
  - unzip /tmp/ctrulib.zip
  - cd ctrulib-master/libctru
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/fincs/citro3d/zip/next -O /tmp/citro3d.zip
  - unzip /tmp/citro3d.zip
  - cd citro3d-master
  - make && sudo make install
  - cd ..  
  - wget --no-check-certificate https://github.com/xerpi/3ds_portlibs/releases/download/1/portlibs-linux.zip -O /tmp/3ds_portlibs.zip
  - unzip /tmp/3ds_portlibs.zip
  - sudo cp -R portlibs ${DEVKITPRO}/
  - wget --no-check-certificate https://codeload.github.com/xerpi/sf2dlib/zip/master -O /tmp/sf2dlib.zip
  - unzip /tmp/sf2dlib.zip
  - cd sf2dlib-master/libsf2d
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/xerpi/sfillib/zip/master -O /tmp/sfillib.zip
  - unzip /tmp/sfillib.zip
  - cd sfillib-master/libsfil
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate https://codeload.github.com/xerpi/sftdlib/zip/master -O /tmp/sftdlib.zip
  - unzip /tmp/sftdlib.zip
  - cd sftdlib-master/libsftd
  - make && sudo make install
  - cd ../..
  - wget --no-check-certificate  https://raw.githubusercontent.com/libretro/RetroArch/master/ctr/tools/bannertool-linux
  - chmod 777 bannertool-linux
  - sudo cp bannertool-linux /usr/bin/bannertool
  - wget --no-check-certificate  https://raw.githubusercontent.com/libretro/RetroArch/master/ctr/tools/makerom-linux
  - chmod 777 makerom-linux
  - sudo cp makerom-linux /usr/bin/makerom
  - wget --no-check-certificate https://codeload.github.com/ahezard/libnds/zip/master -O /tmp/libnds.zip
  - unzip /tmp/libnds.zip
  - cd libnds-master
  - make && sudo make install
  - cd ..  
script:
  - echo "Starting compilation"
  - cd twlnand-side
  - echo "Compiling TWLoader NAND Side"
  - make
  - cd ..
  - echo "Compiling TWLoader GUI"
  - cd gui
  - make
  - echo "Compilation ended"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libstdc++6
    - lftp