language: cpp
os: linux
dist: trusty
sudo: required

python:
    - "2.7"
    - "3.6"
before_install:
  - sudo apt-get update --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
  - pyenv global system 3.6
  - wget https://github.com/devkitPro/installer/releases/download/v2.1.0/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM

install:
  - sudo wget -P /usr/local/share/ca-certificates https://curl.haxx.se/ca/cacert.pem -O cacert.crt
  - sudo update-ca-certificates
  - sudo perl devkitARMupdate.pl  
  - wget https://github.com/xerpi/3ds_portlibs/releases/download/1/portlibs-linux.zip -O /tmp/3ds_portlibs.zip
  - unzip /tmp/3ds_portlibs.zip
  - sudo cp -R portlibs ${DEVKITPRO}/
  - wget  https://raw.githubusercontent.com/Steveice10/buildtools/1ea00aaa369d80a825002e5d514dddff2305f88b/3ds/bannertool-linux64
  - chmod 777 bannertool-linux64
  - sudo cp bannertool-linux64 /usr/bin/bannertool
  - wget https://raw.githubusercontent.com/Steveice10/buildtools/1ea00aaa369d80a825002e5d514dddff2305f88b/3ds/makerom-linux64
  - chmod 777 makerom-linux64
  - sudo cp makerom-linux64 /usr/bin/makerom
  - python3.6 -m pip install requests
  - python3.6 -m pip install gitpython
script:
  - echo "Starting compilation"
  - echo "Patching Nightly"
  - python3.6 Nightlies/patch-nightly.py
  - cd twlnand-stage1
  - echo "Compiling TWLoader NAND Side Stage 1 (part 1)"
  - make
  - python patch_ndsheader_dsiware.py Stage1.nds --mode dsi --maker 01 --code TWLD --title "TWLOADER-TWL" --out Stage1-DSiWare.nds
  - chmod +x ./make_cia
  - ./make_cia --srl="Stage1-DSiWare.nds"
  - cd ..
  - cd NTR_Launcher
  - echo "Compiling TWLoader NAND Side Stage 1 (part 2)"
  - make
  - chmod +x ./make_cia
  - ./make_cia --srl="NTR_Launcher.nds"
  - cd ..
  - cd twlnand-stage2
  - echo "Compiling TWLoader NAND Side Stage 2"
  - make
  - cd ..
  - echo "Compiling TWLoader GUI (cia)"
  - cd gui
  - make -j8 COMPILE_3DSX=0 IS_NIGHTLY=1
  - cd ..
  - echo "Creating release ZIP"
  - mkdir "Nightly"
  - cd "twlnand-stage1"
  - cp "Stage1-DSiWare.cia" "../Nightly/TWLoader - TWLNAND side.cia"
  - cd ..
  - cd NTR_Launcher
  - cp "NTR_Launcher.cia" "../Nightly/TWLoader -TWLNAND Side (part 2).cia"
  - cd ..
  - cd "twlnand-stage2"
  - cp "Stage2.nds" "../Nightly/TWLD.twldr"
  - cd ..
  - cd gui
  - cp "TWLoader.cia" "../Nightly/TWLoader.cia"
  - cd ..
  - cd "Nightly"
  - zip "TWLoader.zip" *
  - dir
  - cd ..
  - echo "Compilation ended"
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python3.6 Nightlies/upload-nightly.py; fi'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libstdc++6
    - lftp
env:
  matrix:
    secure: Ufv7yuFpUsJu/ooXbR3NFjG4PrNcFWFm0nGTh46HuVudUdZrmT9w8TNe3IvfDA1sKg5qpjbfZmO36MUvaH252qHUE1I3sPxR6wRax9GGuJmV/fTS3lrWLvW3ytmbdd87lk33YteNJYCEiWX+dvudsSL77owjKgMc2YGweX337sTdy/t5vcw0qdv+a3Hl+hnngDrBN+Gevvwji0/r3LEJAyB6xPsQBKyBLPyXbPf9V4ESTcV/Kqc64fwd+jODgl+246NtmzEoNOQIcxtDR8YgcrYNpidMnkf/BebzV/4HHONQKCiSzP8KnMto6ctFi91IxK8Ye6Y8K0ZNBAxHu3edzO2UfhKaKfSbIZnepB48ZnB+qMOlXg+d7oFpFOt4oMOHk9pKq91WtZy8qfVdYgv2HnfpI1C2wh0CD7SvkGddxwHZ7J4RA01HcArzTkAYArgkL8HJQPE2BaCggPBPhTaeC/F4VO+06/3QpaPaiv6ptOoBRaYME5Wn8tTO3VzeYjgkHc0taUDFYOuGdJqSaLsLjyazo1+dzTpcHo3BX2Ue3p7Ao6eVcGbKVB51H5wrlGutCk0DMUPtyYM3mwTRt8NExSeB7fTIVZpA/UrlKsFuog/NcZbNi2OfyjDUqqHpbulLFYm6ulwSAtdb7dffjCAFmmxGVwcF0utX2Vz6qTQf0ks=
